# Enable validating this file
version: ~> 1.0

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/builds


jobs:
  include:
    - install:
      - pip install -U platformio
      - platformio update
      script: ./build_arduino.sh
      name: "build Arduno"
    - script: ./test.sh
      name: "unit tests"
